### ISSUE TITLE
Post is failing

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/cache-validation#16]
The following Github Action snippet is failing with the error below:

```yaml
    - name: Validate wheel cache
      uses: techservicesillinois/cache-validation@v1
      id: cache
      with:
        path: cache
        cache_hit: ${{ steps.ghcache.outputs.cache-hit }}
        remove_invalid_files: true
        touch: true
```

Github Action [error](https://github.com/techservicesillinois/awscli-login/runs/7796341076?check_suite_focus=true):

```
Post job cleanup.
EEXIST: file already exists, open 'cache/MD5SUMS'
Total files hashed 0.
```

For context the `Validate wheel cache` step returned:

```
Run techservicesillinois/cache-validation@v1
Cache miss: nothing to validate.
```
